import { NextRequest, NextResponse } from "next/server";
import { getBookingsByCustomer, createBooking } from "@/db/queries/bookings";
import { createBookingSchema } from "@/lib/validations";
import { auth } from "@/lib/auth";

export async function GET(_request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ data: null, error: "Unauthorized" }, { status: 401 });
    }

    const result = await getBookingsByCustomer(session.user.id);
    return NextResponse.json({ data: result, error: null }, { status: 200 });
  } catch (err) {
    console.error("[GET /api/bookings]", err);
    return NextResponse.json({ data: null, error: "Internal server error" }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ data: null, error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const parsed = createBookingSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { data: null, error: parsed.error.flatten().fieldErrors },
        { status: 400 }
      );
    }

    // bookingRef is generated by DB trigger — pass empty string, DB will override
    const booking = await createBooking({
      ...parsed.data,
      customerId: session.user.id,
      bookingRef: "", // overridden by trigger
    });

    return NextResponse.json({ data: booking, error: null }, { status: 201 });
  } catch (err) {
    console.error("[POST /api/bookings]", err);
    return NextResponse.json({ data: null, error: "Internal server error" }, { status: 500 });
  }
}
